---
type: specs.openrewrite.org/v1beta/recipe
name: com.github.jbduncan.rewrite.CodeCleanup
recipeList:
  - org.openrewrite.gradle.MigrateToGradle8
  - org.openrewrite.java.RemoveObjectsIsNull
  - org.openrewrite.java.ShortenFullyQualifiedTypeReferences
  - org.openrewrite.java.UseStaticImport:
      methodPattern: java.util.Collections *(..)
  - org.openrewrite.java.UseStaticImport:
      methodPattern: com.google.common.collect.Queues *(..)
  - org.openrewrite.java.UseStaticImport:
      methodPattern: com.google.common.collect.Sets *(..)
  - org.openrewrite.java.dependencies.DependencyVulnerabilityCheck
  - org.openrewrite.java.format.BlankLines
  - org.openrewrite.java.format.MethodParamPad
  - org.openrewrite.java.format.NoWhitespaceAfter
  - org.openrewrite.java.format.NoWhitespaceBefore
  - org.openrewrite.java.format.PadEmptyForLoopComponents
  - org.openrewrite.java.format.RemoveTrailingWhitespace
  - org.openrewrite.java.jspecify.MigrateToJspecify
  - org.openrewrite.java.migrate.UpgradeToJava21
  - org.openrewrite.java.migrate.UseJavaUtilBase64
  - org.openrewrite.java.migrate.concurrent.JavaConcurrentAPIs
  - org.openrewrite.java.migrate.guava.NoGuavaAtomicsNewReference
  - org.openrewrite.java.migrate.guava.NoGuavaCreateTempDir
  - org.openrewrite.java.migrate.guava.NoGuavaDirectExecutor
  - org.openrewrite.java.migrate.guava.NoGuavaListsNewArrayList
  - org.openrewrite.java.migrate.guava.NoGuavaListsNewCopyOnWriteArrayList
  - org.openrewrite.java.migrate.guava.NoGuavaListsNewLinkedList
  - org.openrewrite.java.migrate.guava.NoGuavaMapsNewTreeMap
  - org.openrewrite.java.migrate.guava.NoGuavaRefasterRecipes
  - org.openrewrite.java.migrate.guava.NoGuavaSetsNewConcurrentHashSet
  - org.openrewrite.java.migrate.guava.NoGuavaSetsNewHashSet
  - org.openrewrite.java.migrate.guava.NoGuavaSetsNewLinkedHashSet
  - org.openrewrite.java.migrate.guava.PreferCharCompare
  - org.openrewrite.java.migrate.guava.PreferIntegerCompare
  - org.openrewrite.java.migrate.guava.PreferIntegerCompareUnsigned
  - org.openrewrite.java.migrate.guava.PreferIntegerDivideUnsigned
  - org.openrewrite.java.migrate.guava.PreferIntegerParseUnsignedInt
  - org.openrewrite.java.migrate.guava.PreferJavaNioCharsetStandardCharsets
  - org.openrewrite.java.migrate.guava.PreferJavaStringJoin
  - org.openrewrite.java.migrate.guava.PreferJavaUtilCollectionsSynchronizedNavigableMap
  - org.openrewrite.java.migrate.guava.PreferJavaUtilCollectionsUnmodifiableNavigableMap
  - org.openrewrite.java.migrate.guava.PreferJavaUtilFunction
  - org.openrewrite.java.migrate.guava.PreferJavaUtilObjectsEquals
  - org.openrewrite.java.migrate.guava.PreferJavaUtilObjectsHashCode
  - org.openrewrite.java.migrate.guava.PreferJavaUtilObjectsRequireNonNullElse
  - org.openrewrite.java.migrate.guava.PreferJavaUtilOptional
  - org.openrewrite.java.migrate.guava.PreferJavaUtilPredicate
  - org.openrewrite.java.migrate.guava.PreferJavaUtilSupplier
  - org.openrewrite.java.migrate.guava.PreferLongCompare
  - org.openrewrite.java.migrate.guava.PreferLongCompareUnsigned
  - org.openrewrite.java.migrate.guava.PreferLongDivideUnsigned
  - org.openrewrite.java.migrate.guava.PreferLongParseUnsignedLong
  - org.openrewrite.java.migrate.guava.PreferLongRemainderUnsigned
  - org.openrewrite.java.migrate.guava.PreferMathAddExact
  - org.openrewrite.java.migrate.guava.PreferMathClamp
  - org.openrewrite.java.migrate.guava.PreferMathMultiplyExact
  - org.openrewrite.java.migrate.guava.PreferMathSubtractExact
  - org.openrewrite.java.migrate.guava.PreferShortCompare
  - org.openrewrite.java.migrate.io.ReplaceFileInOrOutputStreamFinalizeWithClose
  - org.openrewrite.java.migrate.lang.JavaLangAPIs
  - org.openrewrite.java.migrate.lang.StringFormatted
  - org.openrewrite.java.migrate.lang.StringRulesRecipes
  - org.openrewrite.java.migrate.lang.UseStringIsEmptyRecipe
  - org.openrewrite.java.migrate.lang.UseTextBlocks
  - org.openrewrite.java.migrate.logging.JavaLoggingAPIs
  - org.openrewrite.java.migrate.net.JavaNetAPIs
  - org.openrewrite.java.migrate.net.URLConstructorsToURIRecipes
  - org.openrewrite.java.migrate.util.OptionalStreamRecipe
  - org.openrewrite.java.migrate.util.SequencedCollection
  - org.openrewrite.java.testing.assertj.AdoptAssertJDurationAssertions
  - org.openrewrite.java.testing.assertj.Assertj
  - org.openrewrite.java.testing.cleanup.AssertLiteralBooleanToFailRecipe
  - org.openrewrite.java.testing.cleanup.AssertTrueNullToAssertNull
  - org.openrewrite.java.testing.cleanup.RemoveEmptyTests
  - org.openrewrite.java.testing.cleanup.RemoveTestPrefix
  - org.openrewrite.java.testing.cleanup.TestsShouldNotBePublic
  - org.openrewrite.java.testing.junit5.AddParameterizedTestAnnotation
  - org.openrewrite.java.testing.junit5.AssertThrowsOnLastStatement
  - org.openrewrite.java.testing.junit5.CleanupAssertions
  - org.openrewrite.java.testing.junit5.JUnit4to5Migration
  - org.openrewrite.java.testing.junit5.LifecycleNonPrivate
  - org.openrewrite.java.testing.junit5.RemoveDuplicateTestTemplates
  - org.openrewrite.java.testing.junit5.StaticImports
  - org.openrewrite.java.testing.mockito.ReplacePowerMockito
  - org.openrewrite.kotlin.cleanup.EqualsMethodUsage
  - org.openrewrite.kotlin.cleanup.ImplicitParameterInLambda
  - org.openrewrite.kotlin.cleanup.ReplaceCharToIntWithCode
  - org.openrewrite.recommendations.CodeHealth
  - org.openrewrite.staticanalysis.AddSerialVersionUidToSerializable
  - org.openrewrite.staticanalysis.AtomicPrimitiveEqualsUsesGet
  - org.openrewrite.staticanalysis.BigDecimalDoubleConstructorRecipe
  - org.openrewrite.staticanalysis.BigDecimalRoundingConstantsToEnums
  - org.openrewrite.staticanalysis.BooleanChecksNotInverted
  - org.openrewrite.staticanalysis.CaseInsensitiveComparisonsDoNotChangeCase
  - org.openrewrite.staticanalysis.CatchClauseOnlyRethrows
  - org.openrewrite.staticanalysis.ChainStringBuilderAppendCalls
  - org.openrewrite.staticanalysis.CodeCleanup
  - org.openrewrite.staticanalysis.CombineSemanticallyEqualCatchBlocks
  - org.openrewrite.staticanalysis.CommonDeclarationSiteTypeVariances
  - org.openrewrite.staticanalysis.CompareEnumsWithEqualityOperator
  - org.openrewrite.staticanalysis.CovariantEquals
  - org.openrewrite.staticanalysis.DefaultComesLast
  - org.openrewrite.staticanalysis.EmptyBlock
  - org.openrewrite.staticanalysis.EqualsAvoidsNull
  - org.openrewrite.staticanalysis.EqualsToContentEquals
  - org.openrewrite.staticanalysis.ExplicitCharsetOnStringGetBytes
  - org.openrewrite.staticanalysis.ExplicitInitialization
  - org.openrewrite.staticanalysis.ExternalizableHasNoArgsConstructor
  - org.openrewrite.staticanalysis.FallThrough
  - org.openrewrite.staticanalysis.FinalClass
  - org.openrewrite.staticanalysis.FinalizePrivateFields
  - org.openrewrite.staticanalysis.FixStringFormatExpressions
  - org.openrewrite.staticanalysis.ForLoopControlVariablePostfixOperators
  - org.openrewrite.staticanalysis.ForLoopIncrementInUpdate
  - org.openrewrite.staticanalysis.HiddenField
  - org.openrewrite.staticanalysis.HideUtilityClassConstructor
  - org.openrewrite.staticanalysis.IndexOfChecksShouldUseAStartPosition
  - org.openrewrite.staticanalysis.IndexOfReplaceableByContains
  - org.openrewrite.staticanalysis.IndexOfShouldNotCompareGreaterThanZero
  - org.openrewrite.staticanalysis.InlineVariable
  - org.openrewrite.staticanalysis.InstanceOfPatternMatch
  - org.openrewrite.staticanalysis.IsEmptyCallOnCollections
  - org.openrewrite.staticanalysis.JavaApiBestPractices
  - org.openrewrite.staticanalysis.LambdaBlockToExpression
  - org.openrewrite.staticanalysis.LowercasePackage
  - org.openrewrite.staticanalysis.MethodNameCasing
  - org.openrewrite.staticanalysis.MinimumSwitchCases
  - org.openrewrite.staticanalysis.MissingOverrideAnnotation
  - org.openrewrite.staticanalysis.ModifierOrder
  - org.openrewrite.staticanalysis.MultipleVariableDeclarations
  - org.openrewrite.staticanalysis.NeedBraces
  - org.openrewrite.staticanalysis.NewStringBuilderBufferWithCharArgument
  - org.openrewrite.staticanalysis.NoDoubleBraceInitialization
  - org.openrewrite.staticanalysis.NoEmptyCollectionWithRawType
  - org.openrewrite.staticanalysis.NoEqualityInForCondition
  - org.openrewrite.staticanalysis.NoFinalizedLocalVariables
  - org.openrewrite.staticanalysis.NoFinalizer
  - org.openrewrite.staticanalysis.NoPrimitiveWrappersForToStringOrCompareTo
  - org.openrewrite.staticanalysis.NoRedundantJumpStatements
  - org.openrewrite.staticanalysis.NoToStringOnStringType
  - org.openrewrite.staticanalysis.NoValueOfOnStringType
  - org.openrewrite.staticanalysis.ObjectFinalizeCallsSuper
  - org.openrewrite.staticanalysis.OperatorWrap
  - org.openrewrite.staticanalysis.PrimitiveWrapperClassConstructorToValueOf
  - org.openrewrite.staticanalysis.RedundantFileCreation
  - org.openrewrite.staticanalysis.ReferentialEqualityToObjectEquals
  - org.openrewrite.staticanalysis.RemoveCallsToSystemGc
  - org.openrewrite.staticanalysis.RemoveExtraSemicolons
  - org.openrewrite.staticanalysis.RemoveHashCodeCallsFromArrayInstances
  - org.openrewrite.staticanalysis.RemoveRedundantTypeCast
  - org.openrewrite.staticanalysis.RemoveToStringCallsFromArrayInstances
  - org.openrewrite.staticanalysis.RemoveUnneededAssertion
  - org.openrewrite.staticanalysis.RemoveUnneededBlock
  - org.openrewrite.staticanalysis.RemoveUnusedLocalVariables
  - org.openrewrite.staticanalysis.RemoveUnusedPrivateFields
  - org.openrewrite.staticanalysis.RemoveUnusedPrivateMethods
  - org.openrewrite.staticanalysis.RenameLocalVariablesToCamelCase
  - org.openrewrite.staticanalysis.RenamePrivateFieldsToCamelCase
  - org.openrewrite.staticanalysis.ReplaceClassIsInstanceWithInstanceof
  - org.openrewrite.staticanalysis.ReplaceDeprecatedRuntimeExecMethods
  - org.openrewrite.staticanalysis.ReplaceDuplicateStringLiterals
  - org.openrewrite.staticanalysis.ReplaceLambdaWithMethodReference
  - org.openrewrite.staticanalysis.ReplaceOptionalIsPresentWithIfPresent
  - org.openrewrite.staticanalysis.ReplaceRedundantFormatWithPrintf
  - org.openrewrite.staticanalysis.ReplaceStackWithDeque
  - org.openrewrite.staticanalysis.ReplaceStringBuilderWithString
  - org.openrewrite.staticanalysis.ReplaceThreadRunWithThreadStart
  - org.openrewrite.staticanalysis.ReplaceWeekYearWithYear
  - org.openrewrite.staticanalysis.SimplifyBooleanExpression
  - org.openrewrite.staticanalysis.SimplifyBooleanReturn
  - org.openrewrite.staticanalysis.SimplifyCompoundStatement
  - org.openrewrite.staticanalysis.SimplifyConsecutiveAssignments
  - org.openrewrite.staticanalysis.SimplifyConstantIfBranchExecution
  - org.openrewrite.staticanalysis.SimplifyDurationCreationUnits
  - org.openrewrite.staticanalysis.SortedSetStreamToLinkedHashSet
  - org.openrewrite.staticanalysis.StaticMethodNotFinal
  - org.openrewrite.staticanalysis.StringLiteralEquality
  - org.openrewrite.staticanalysis.TypecastParenPad
  - org.openrewrite.staticanalysis.UnnecessaryCatch
  - org.openrewrite.staticanalysis.UnnecessaryCloseInTryWithResources
  - org.openrewrite.staticanalysis.UnnecessaryExplicitTypeArguments
  - org.openrewrite.staticanalysis.UnnecessaryParentheses
  - org.openrewrite.staticanalysis.UnnecessaryPrimitiveAnnotations
  - org.openrewrite.staticanalysis.UnnecessaryReturnAsLastStatement
  - org.openrewrite.staticanalysis.UnnecessaryThrows
  - org.openrewrite.staticanalysis.UnwrapRepeatableAnnotations
  - org.openrewrite.staticanalysis.UpperCaseLiteralSuffixes
  - org.openrewrite.staticanalysis.UseCollectionInterfaces
  - org.openrewrite.staticanalysis.UseDiamondOperator
  - org.openrewrite.staticanalysis.UseForEachRemoveInsteadOfSetRemoveAll
  - org.openrewrite.staticanalysis.UseJavaStyleArrayDeclarations
  - org.openrewrite.staticanalysis.UseLambdaForFunctionalInterface
  - org.openrewrite.staticanalysis.UseListSort
  - org.openrewrite.staticanalysis.UseMapContainsKey
  - org.openrewrite.staticanalysis.UseStandardCharset
  - org.openrewrite.staticanalysis.UseStringReplace
  - org.openrewrite.staticanalysis.UseSystemLineSeparator
  - org.openrewrite.staticanalysis.WhileInsteadOfFor
  - org.openrewrite.staticanalysis.WriteOctalValuesAsDecimal
---
type: specs.openrewrite.org/v1beta/recipe
name: com.github.jbduncan.rewrite.SecurityBestPractices
recipeList:
  - org.openrewrite.gradle.security.UseHttpsForRepositories
  - org.openrewrite.java.search.FindSecrets
  - org.openrewrite.java.security.FindTextDirectionChanges
  - org.openrewrite.java.security.FixCwe338
  - org.openrewrite.java.security.JavaSecurityBestPractices
  - org.openrewrite.java.security.OwaspTopTen
  - org.openrewrite.java.security.RegularExpressionDenialOfService
  - org.openrewrite.java.security.SecureRandom
  - org.openrewrite.java.security.SecureRandomPrefersDefaultSeed
